= Volume Shadow Snapshot (VSS)
Analysis the Windows NT VSS format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

As of Windows Vista the Volume Shadow Snapshot (VSS) stores persistent shadow
copies on the local NTFS volume. This specification is based on publicly
available work on the format and was enhanced by analyzing test data.

This document is intended as a working document of the data format specification
for the libvshadow project.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Volume Shadow Snapshot (VSS) format
| Classification: | Public
| Keywords: | Volume Shadow Snapshot, VSS
|===

[preface]
== License

....
Copyright (C) 2011-2022, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | March 2011 | Initial version, based on earlier notes.
| 0.0.2 | J.B. Metz | March 2011 | April 2011 +
Changes after initial feedback by B. Schatz and new findings.
| 0.0.3 | J.B. Metz | May 2011 | Changes regarding block descriptors and Windows Vista.
| 0.0.4 | J.B. Metz | November 2011 +
December 2011 | Updates regarding block descriptors.
| 0.0.5 | J.B. Metz | April 2012 | Additional information.
| 0.0.6 | J.B. Metz | May 2012 | Additional information about bitmaps. +
Updates for Windows 8 Consumer Preview.
| 0.0.7 | J.B. Metz | August 2012 | Updates and corrections.
| 0.0.8 | J.B. Metz | August 2012 | Additional findings.
| 0.0.9 | J.B. Metz | September 2012 | Updates and corrections. Additional findings regarding overlays.
| 0.0.10 | J.B. Metz | September 2012 | Additional findings regarding catalog entries and corruption scenarios with thanks to R. Lee.
| 0.0.11 | J.B. Metz | November 2012 | Additional findings regarding Windows 2003 R2 (SP2).
| 0.0.12 | J.B. Metz | May 2013 | Small changes.
| 0.0.13 | J.B. Metz | December 2014 | Switched to asccidoc format.
| 0.0.14 | J.B. Metz | January 2016 | Small changes.
| 0.0.15 | J.B. Metz | March 2019 | asciidoc format changes.
| 0.0.16 | J.B. Metz | May 2020 | Added note about scoped snapshots.
| 0.0.17 | J.B. Metz | August 2022 | Formatting changes.
|===

:numbered:
== Overview

As of Windows Vista the Volume Shadow Snapshot (VSS) stores persistent shadow
copies on the local NTFS volume.

According to `[MSDN]` a shadow copy is a snapshot of a volume. A shadow copy can
be part of a set which contains a collection of shadow copies of various
volumes, taken at the same time.

[yellow-background]*Does a set always contains a single shadow copy per volume?*

VSS can use different providers to store shadow copies, this document focuses
on "Microsoft Software Shadow Copy provider 1.0", which uses the GUID:
b5946137-7b9f-4925-af80-51abd60b20d5. This provider stores the copies on the
local volume using 16 KiB blocks.

VSS uses the GUID 3808876b-c176-4e48-b7ae-04046e6cc752 to identify its data or
metadata files. VSS provides for several metadata files in "System Volume
Information":
VSS catalog; stored in the metadata file named {%VSSGUID%}
VSS store; stored in the metadata file named {%GUID%}{%VSSGUID%}

Where %VSSGUID% (_VSP_DIFF_AREA_FILE_GUID) contains the VSS identifier and
%GUID% contains a time/MAC based GUID/UUID.

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | FILETIME in UTC
| Character strings | Unicode strings are stored in UTF-16 little-endian without the byte order mark (BOM).
|===

=== Test version

The following version of programs were used to test the information within this document:

* Windows 2003 R2 (SP2)
* Windows Vista
* Windows 2008
* Windows 7
* Windows 8 (Consumer Preview)
* [yellow-background]*TODO: Windows 2012*
* [yellow-background]*TODO: Windows 10*

==  Volume header

The VSS volume header is part of the NTFS volume header (or $Boot metadata
file). The VSS volume header data is stored at offset 7680 (0x1e00) of the
volume and is at least 100 bytes in size ([yellow-background]*but probably 512 bytes, sector size*)
and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | VSS identifier +
Contains a GUID
| 16 | 4 | | Version
| 20 | 4 | 0x01 | Record type
| 24 | 8 | 0x1e00 | Current offset +
The offset is relative to the start of the volume
| 32 | 8 | [yellow-background]*0x1e00* | [yellow-background]*Unknown (Next offset?)* +
The offset is relative to the start of the volume
| 40 | 8 | | [yellow-background]*Unknown (empty value)*
| 48 | 8 | | Catalog offset +
The offset is relative to the start of the volume +
0 if no catalog
| 56 | 8 | | Maximum size +
0 if unbounded
| 64 | 16 | | [yellow-background]*Volume identifier* +
Contains a GUID
| 80 | 16 | | [yellow-background]*Shadow copy storage volume identifier* +
Contains a GUID
| 96 | 4 | | [yellow-background]*Unknown*
| 100 | 412 | | [yellow-background]*Unknown (empty values)*
|===

=== Version

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 1 | | Windows Vista, 7
| 2 | | Windows 8
|===

== Catalog

The catalog contains information about the individual stores. The catalog
consists of one or more catalog blocks. Each catalog block is 16384 (0x4000)
bytes of size and consists of:

* catalog block header
* an array of catalog entries

The VSS catalog metadata files contains the catalog blocks stored directly
after one-and-other.

If the volume does not contain a catalog when there are no snapshots (stored)
but VSS is enabled.

=== Catalog block header

The catalog block header is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | VSS identifier +
Contains a GUID
| 16 | 4 | 0x01 | Version
| 20 | 4 | 0x02 | Record type
| 24 | 8 | | Relative (catalog block) offset +
The offset is relative to the start of the first catalog block
| 32 | 8 | | Current (catalog block) offset +
The offset is relative to the start of the volume
| 40 | 8 | | Next (catalog block) offset +
The offset is relative to the start of the volume. +
Contains 0 if this is the last block.
| 48 | 80 | | [yellow-background]*Unknown (empty values)*
|===

=== Catalog entry

Each catalog entry consists of a catalog entry type 0x02. A corresponding type
0x03 is required if the shadow copy is stored in a store, which is the case as
of Windows Vista.

[NOTE]
A Windows 2003 R2 catalog does not contain catalog entry type 0x03.

[yellow-background]*How does Windows 2003 R2 volumes store the snapshot data?*

The type 0x02 and type 0x03 entries are not necessarily stored directly after
one-and-other and can be scattered over the catalog. For now it is assumed that
entry type 0x02 must be defined before entry type 0x03.

Also these entries are not necessarily stored in order of age.

There can be unused catalog entries (of type 0x01) as well. Empty catalog
entries seem to consist entirely of 0-bytes.

==== Unused catalog entry (type 0x01)

An unused catalog entry (type 0x01) is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | 0x01 | Catalog entry type
| 8 | 120 | | [yellow-background]*Unknown (empty values)*
|===

==== Catalog entry type 0x02

A catalog entry type 0x02 is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | 0x02 | Catalog entry type
| 8 | 8 | | Volume size
| 16 | 16 | | Store identifier +
Contains a GUID +
This GUID is used in the store filename
| 32 | 8 | | [yellow-background]*Unknown (Sequence number)*
| 40 | 8 | | [yellow-background]*Unknown (Flags?)* +
[yellow-background]*0x40 => windows in vista and 7* +
[yellow-background]*0x440 => in windows 8 (file backup?)*
| 48 | 8 | | Shadow copy creation time +
Contains a FILETIME
| 56 | 72 | | [yellow-background]*Unknown (empty values)*
|===

==== Catalog entry type 0x03

A catalog entry type 0x03 is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | 0x03 | Catalog entry type
| 8 | 8 | | Store block list offset +
The offset is relative to the start of the volume
| 16 | 16 | | Store identifier +
Contains a GUID +
This GUID is used in the store filename
| 32 | 8 | | Store header offset +
The offset is relative to the start of the volume
| 40 | 8 | | Store block range list offset +
The offset is relative to the start of the volume
| 48 | 8 | | Store (current) bitmap offset +
The offset is relative to the start of the volume
| 56 | 8 | | NTFS (metadata) file reference
| 64 | 8 | | [yellow-background]*Allocated size*
| 72 | 8 | | Store previous bitmap offset +
The offset is relative to the start of the volume or 0 if not used
| 80 | 8 | | [yellow-background]*Unknown* +
[yellow-background]*Looks like store index but assumption does not hold*
| 88 | 40 | | [yellow-background]*Unknown (empty)*
|===

== Store

The store contains information about the shadow volume; it actually contains
copies of previous versions of data blocks on the volume.

The stores must be applied starting with the most recent on top of the current
volume. E.g. if there are 3 stores and we want to access the state of the
oldest (number 1) we must first apply the changes in store 3 over the current
volume, the changes in store 2 over the resulting volume, and finally the
changes in store 1 over the resulting volume.

The store consists of:

* store header
* store block list
* store block range list
* store bitmaps
* data blocks

=== Store block header

The store block header is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | VSS identifier +
Contains a GUID
| 16 | 4 | 0x01 | Version
| 20 | 4 | | Record type
| 24 | 8 | | Relative (block) offset +
The offset is relative to the start of the store
| 32 | 8 | | Current (block) offset +
The offset is relative to the start of the volume
| 40 | 8 | | Next (block) offset +
The offset is relative to the start of the volume +
Contains 0 if this is the last block.
| 48 | 8 | | Size of store information +
Only used in first block header +
Should be 0 in other block headers
| 56 | 72 | | [yellow-background]*Unknown (empty value)*
|===

==== Store block record types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | | [yellow-background]*Unknown*
| 0x0001 | | Volume header
| 0x0002 | | Catalog block header
| 0x0003 | | Block descriptor list +
(Diff area table)
| 0x0004 | | Store header
| 0x0005 | | [yellow-background]*Store block ranges list*
| 0x0006 | | Store bitmap
|===

===== Notes

[yellow-background]*TODO: Are these values related to VSS_MGMT_OBJECT_TYPE?*

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | VSS_MGMT_OBJECT_UNKNOWN |
| 0x0001 | VSS_MGMT_OBJECT_VOLUME |
| 0x0002 | VSS_MGMT_OBJECT_DIFF_VOLUME |
| 0x0003 | VSS_MGMT_OBJECT_DIFF_AREA |
|===

=== Store information

The store information is stored directly after the store header.

The store information is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | [yellow-background]*Unknown (identifier?)* +
[yellow-background]*Contains a GUID*
| 16 | 16 | | Shadow copy identifier +
Contains a GUID
| 32 | 16 | | Shadow copy set identifier +
Contains a GUID
| 48 | 4 | | Snapshot context +
See section: <<store_snapshot_context,Store snapshot context>>
| 52 | 4 | | [yellow-background]*Unknown (Provider?)*
| 56 | 4 | | Attribute flags +
See section: <<store_attribute_flags,Store attribute flags>>
| 60 | 4 | | [yellow-background]*Unknown (empty values)*
| 64 | 2 | | Operating machine string size +
Contains the number of bytes
| 66 | (size) | | Operating machine string +
Contains Unicode string without end-of-string character
| ... | 2 | | Service machine string size +
Contains the number of bytes
| ... | (size) | | Service machine string +
Contains Unicode string without end-of-string character
| ...  | ...  | | [yellow-background]*Unknown (empty value)*
|===

[NOTE]
The difference between the operating machine and the service machine is
currently unknown.

==== [[store_snapshot_context]]Store snapshot context

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | VSS_CTX_BACKUP +
Backup | Standard backup context
| | |
| 0x00000009 | VSS_CTX_APP_ROLLBACK +
ApplicationRollback | Persistent shadow copy
| | |
| 0x0000000d | VSS_CTX_CLIENT_ACCESSIBLE_WRITERS +
ClientAccessibleWriters | Read-only shadow copy created with writer involvement
| | |
| 0x00000010 | VSS_CTX_FILE_SHARE_BACKUP | Non-persistent shadow copy created
| | |
| 0x00000019 | VSS_CTX_NAS_ROLLBACK | Persistent shadow copy of a NAS volume
| | |
| 0x0000001d | VSS_CTX_CLIENT_ACCESSIBLE | Read-only shadow copy for Shared Folders
| | |
| 0xffffffff | VSS_CTX_ALL | All types of shadow copy are available for administrative operations
|===

[NOTE]
The store snapshot context value is a combination of (some of the) store attribute flags.

==== [[store_attribute_flags]]Store attribute flags

`[MSDN]` refers to the store attribute flags as _VSS_VOLUME_SNAPSHOT_ATTRIBUTES.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | VSS_VOLSNAP_ATTR_PERSISTENT | Is persistent +
The shadow copy is persistent across reboots
| 0x00000002 | VSS_VOLSNAP_ATTR_NO_AUTORECOVERY | Auto-recovery is disabled +
[yellow-background]*(Previously named: VSS_VOLSNAP_ATTR_READ_WRITE)* +
[yellow-background]*Not shown by vssadmin*
| 0x00000004 | VSS_VOLSNAP_ATTR_CLIENT_ACCESSIBLE | Is client-accessible +
The specified shadow copy is a client-accessible.
| 0x00000008 | VSS_VOLSNAP_ATTR_NO_AUTO_RELEASE | No auto release +
The shadow copy is not automatically deleted when the shadow copy requester process ends.
| 0x00000010 | VSS_VOLSNAP_ATTR_NO_WRITERS | Has no writers +
No writers are involved in creating the shadow copy.
| 0x00000020 | VSS_VOLSNAP_ATTR_TRANSPORTABLE | Is transportable +
The shadow copy is to be transported and therefore should not be exposed locally.
| 0x00000040 | VSS_VOLSNAP_ATTR_NOT_SURFACED | Not surfaced (not exposed) +
The shadow copy is not currently exposed.
| 0x00000080 | VSS_VOLSNAP_ATTR_NOT_TRANSACTED | Not transacted +
The shadow copy is not transacted. +
[yellow-background]*Not shown by vssadmin*
| | |
| 0x00010000 | VSS_VOLSNAP_ATTR_HARDWARE_ASSISTED | (Provider) is hardware assisted +
Indicates that a given provider is a hardware provider.
| 0x00020000 | VSS_VOLSNAP_ATTR_DIFFERENTIAL | (Provider) is differential +
Indicates that a given provider uses differential data or a copy-on-write mechanism to implement shadow copies.
| 0x00040000 | VSS_VOLSNAP_ATTR_PLEX | (Provider) is PLEX +
Indicates that a given provider uses a PLEX or mirrored split mechanism to implement shadow copies.
| 0x00080000 | VSS_VOLSNAP_ATTR_IMPORTED | Is imported +
The shadow copy of the volume was imported onto this machine.
| 0x00100000 | VSS_VOLSNAP_ATTR_EXPOSED_LOCALLY | Is exposed locally +
The shadow copy is locally exposed.
| 0x00200000 | VSS_VOLSNAP_ATTR_EXPOSED_REMOTELY | Is exposed remotely +
The shadow copy is remotely exposed.
| 0x00400000 | VSS_VOLSNAP_ATTR_AUTORECOVER | Auto recovered +
Indicates that the writer will need to auto-recover the [yellow-background]*on post snapshot*.
| 0x00800000 | VSS_VOLSNAP_ATTR_ROLLBACK_RECOVERY | For rollback recovery +
Indicates that the writer will need to auto-recover the [yellow-background]*on post snapshot* if the snapshot is used for rollback.
| 0x01000000 | VSS_VOLSNAP_ATTR_DELAYED_POSTSNAPSHOT | Delayed post snapshot +
Reserved for system use +
[yellow-background]*Not shown by vssadmin*
| 0x02000000 | VSS_VOLSNAP_ATTR_TXF_RECOVERY | Transactional NTFS (TxF) recovery required +
Indicates that Transactional NTFS (TxF) recovery should be enforced during shadow copy creation.+
[yellow-background]*Not shown by vssadmin*
|===

=== Store block list

The store block list contains information about the data block ranges used by
the snapshot.

The store block list is stored in blocks of 16384 (0x4000) bytes. Each store
block list block consists of:

* a store block header of type 3
* an array of store block descriptors

==== Block descriptor

The block descriptor is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Original data block offset +
The offset is relative to the start of the volume
| 8 | 8 | | Relative store data block offset +
The offset is relative to the start of the store +
[yellow-background]*lower bits used for different purpose?*
| 16 | 8 | | Store data block offset +
The offset is relative to the start of the volume
| 24 | 4 | | Flags
| 28 | 4 | | Allocation bitmap +
[yellow-background]*Used if flag 0x02 is set, otherwise is should contain a value of 0*
|===

==== Store block descriptor flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | | Is forwarder +
The absolute offset is set to 0 and the relative offset maps to the original offset of the next block.
| 0x00000002 | | Overlay +
The block descriptor is an overlay. The allocation bitmap value contains information about the block fill.
| 0x00000004 | | Not used +
If set block is ignored.
| 0x00000008 | | [yellow-background]*Unknown*
| 0x00000010 | | [yellow-background]*Unknown*
| 0x00000020 | | [yellow-background]*Unknown*
| 0x00000040 | | [yellow-background]*Unknown*
| 0x00000080 | | [yellow-background]*Unknown*
|===

===== Notes

[yellow-background]*Note max flags 0xff?*

If flags 0x01 not allowed 0x1a
If flags 0x02 not allowed 0x19
If flags 0x08 not allowed 0x03, allowed 0x10, 0x20, 0x40, 0x80
If flags 0x18
If flags 0x28 not allowed 0x10, 0xc0
If flags 0x48 not allowed 0x10, 0xa0
If flags 0x88 not allowed 0x60

0x00 => mode 0 ?
0x08 => mode 1
0x28 => mode 2
0x48 => mode 3
0x88 => mode 4
0x18 => mode 10 ?

[yellow-background]*0x88 related to journal RCRD?*

[yellow-background]*0x04 can show block wrap behavior, like if its mapped to an unallocated range*

[yellow-background]*Setting flags to 0x10 corrupts the catalog?*

==== Successive block descriptors

[NOTE]
This section is not complete yet, since the meaning of several flags is unknown.

Successive block descriptors with the same original offset are be handled
differently based on their flags and position in the block list. The block list
is scanned front to back.

For the new block descriptor

....
* If the not used flag is set (0x04):
    * Ignore the new block descriptor

* If the overlay flag (0x02) is not set:
    * If there is a corresponding block descriptor in the reverse block list:
      Meaning that the original offset (of the new block descriptor) matches
      the relative offset of a forwarder block descriptor in the reverse block
      list.
        * Replace the original offset with that of the forwarder block
          descriptor in the reverse block list.
        * Remove the forwarder block descriptor from the reverse block list.
        * If the forwarder flag (0x01) (of the new block descriptor) is set:
            * If the original offset (of the new block descriptor) is the same
              as the relative offset:
                * Ignore the new block descriptor

* If no previous block descriptor was found:
    * Add the new block descriptor to the block list.
* Else:
    * If the overlay flag (0x02) is set:
      The new block descriptor contains an overlay. The allocation bitmap
      contains information about which part of the block is used. Every bit
      in the allocation bitmap signifies a block of 512 bytes. The LSB in
      the allocation bitmap represent the first 512 bytes in the block.
      Normally the relative offset is should not be 1, but this seems to be
      ignored if it is.

        * If an existing overlay block descriptor was defined:
            * Extended the existing overlay.
              Normally the relative offset should be 1 and the original offset
              should match that of the existing overlay block descriptor. If
              not these values seem to be ignored and the existing overlay
              is extended with the allocation bitmap in the new block descriptor.
        * Else:
            * Replace the existing block descriptor. Existing overlay block
              descriptors are applied to the new block descriptor.

* If the forwarder flag (0x01) is set:
    * If no previous reverse block descriptor was found:
        * Add the new block descriptor to the reverse block list.
    * Else:
        * Replace the existing reverse block descriptor.
....

=== Store block range list

The store block range list contains information about the data block ranges
used by the store itself. It is probably used to maintain these ranges on the
volume layer, since the corresponding NTFS file entry data runs are applied on
the file system layer.

The store block range list is stored in blocks of 16384 (0x4000) bytes. Each
store block range list block consists of:

* a store block header of type 5
* an array of store block range list entries

==== Store block range entry

The store block range entry is 24 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Store (block range start) offset +
The offset is relative to the start of the volume
| 8 | 8 | | Relative (block range start) offset +
The offset is relative to the start of the store
| 16 | 8 | | Block range size
|===

=== Store bitmap

The store bitmap contains information about the allocation of blocks.

The store bitmap is stored in blocks of 16384 (0x4000) bytes. Each store bitmap
block consists of:

* a store block header of type 6
* a bitmap

==== Store (current) bitmap data

Every bit in the store (current) bitmap represents a block of 16384 (0x4000)
bytes, where the LSB is the first bit in a byte.

If a bit is set, the corresponding block is considered not in-use (or not
allocated) by the store.

The use of this bitmap is described in section: <<reading_snapshot_data,Reading snapshot data>>

==== Store previous bitmap data

Every bit in the store previous bitmap represents a block of 16384 (0x4000)
bytes, where the LSB is the first bit in a byte.

If a bit is set, the corresponding block is not in-use (or not allocated) by
the previous store.

Note that the first store can also contain a previous bitmap if an older store
before it was removed.

The use of this bitmap is described in section: <<reading_snapshot_data,Reading snapshot data>>

=== Store data block

The store data is stored in blocks of 16384 (0x4000) bytes.

=== [[reading_snapshot_data]]Reading snapshot data

For the size of the data that will fit in the buffer:
....
* If the block offset has a corresponding block descriptor:
    * The data is defined by block descriptor and has a maximum size accordingly
    * If this is the active store and the block has an overlay:
        * If the overlay applies:
            * use the overlay block descriptor

    * If the forwarder flag (0x01) is set
      and there is a next store:
        * read the block from the next store using the relative store offset
    * Else:
        * read the block from the current volume using the store offset

* Else:
    * If there is a next store:
        * read the block from the next store
    * Else if the block offset has a corresponding reverse block descriptor:
        * read the block from the current volume
    * Else if the active store is the most recent (last) store
      and the block is flagged in the current bitmap
      and ( the store has no previous bitmap
            or the block is flagged in the previous bitmap ):
        * zero-fill the block
    * Else:
        * read the block from the current volume

    * Increment the block offset with the size of the block data that was read
....

[NOTE]
On Windows the actual behavior of unused block is undefined. A read of a
corresponding block will return successful but will not alter the buffer passed
to the read. For sanitation purposes libvshadow will zero-fill the block.

== Corruption scenarios

This chapter contains several corruption scenarios that have been encountered
"in the wild".

=== Catalog volume size out of bounds

[NOTE]
This currently considered a corruption scenario future findings may or may not
prove otherwise.

The volume size of one of the catalog entries exceeds the size of the
underlying volume and does not corresponds with the volume size defined by the
rest of the catalog entries.

Libvshadow as of 20120915 detects this scenario it will return the corrupt
value as store size but the volume size will be detected based on the NTFS
volume headers if possible.

=== Scope snapshots

Technically scoped snaphots are a feature of volsnapa as of of Windows 8 or
Windws Server 2012 and not a corruption scenario. It has been captured as a
corruption scenario since it leads to some interesting side effects within
file content of the snapshot.

Scope snapshots functionality can be controlled via the Windows Registry value:

....
Key path: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore
Value name: ScopeSnapshots
....

Per `[MCBSYS]` a scope snapshot is a special volume snapshot for volsnap
performance, which is mainly used by Windows critical updates. Scope means
the volsnap only creates Copy on Write (Shadow) volume for the files that
are involved in the updates instead of all the files on the volume.

== Notes

If the VSS_VOLSNAP_ATTR_NO_AUTORECOVERY flag is set in the shadow copy context,
this means that auto-recovery is disabled, and no files can be excluded from
the shadow copy.

The specified shadow copy is a client-accessible shadow copy that supports
Shadow Copies for Shared Folders and should not be exposed.

The device files behave like the CreateFile() FILE_FLAG_NO_BUFFERING flags is
set and can only be read in multitudes of the sector size.

:numbered!:
[appendix]
== References

`[WHITFIELD10]`

[cols="1,5",options="header"]
|===
| Title | Into The Shadows
| Author(s) | Lee Whitfield
| Date | April 19, 2010
| URL | http://www.forensic4cast.com/2010/04/into-the-shadows/
|===

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title | Shadow Copies and Shadow Copy Sets
| URL | http://msdn.microsoft.com/en-us/library/aa384612%28v=vs.85%29.aspx
|===

[cols="1,5",options="header"]
|===
| Title | _VSS_VOLUME_SNAPSHOT_ATTRIBUTES Enumeration
| URL | http://msdn.microsoft.com/en-us/library/aa385012%28v=vs.85%29.aspx\
|===

`[MSDN-VSS]`

[cols="1,5",options="header"]
|===
| Title | Volume Shadow Copy Service Overview
| URL | http://msdn.microsoft.com/en-us/library/windows/desktop/aa384649(v=vs.85).aspx
|===

[cols="1,5",options="header"]
|===
| Title | Excluding Files from Shadow Copies
| URL | http://msdn.microsoft.com/en-us/library/windows/desktop/aa819132(v=vs.85).aspx
|===

`[WIKIPEDIA]`

[cols="1,5",options="header"]
|===
| Title | Shadow Copy
| URL | http://en.wikipedia.org/wiki/Volume_Shadow_Copy_Service
|===

`[MCBSYS]`

[cols="1,5",options="header"]
|===
| Title | Scoped Snapshots vmicvss Error 13 on Server 2012, Windows 8
| Author(s) | Mark Berry
| Date | May 6, 2013
| URL | https://www.mcbsys.com/blog/2013/05/scoped-snapshots-vmicvss-error-13-on-server-2012-windows-8/
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

